### ISSUE TITLE
Bug: Sending funds on chain is increasing shown balance

### ISSUE THREAD

**Issue by niftynei** [clams-tech/App#197]
I sent out a few (unconfirmed) payments using `withdraw`, and it resulted in the displayed balance going up, not down. lol.

The reason for this is that the utxos that were used in the on-chain payment are still in listfunds, as is the change from the tx (but marked as unconfirmed).

Not sure best way to fix, but maybe using the `bkpr-listbalances` would be a more accurate source for node funds than `listfunds`?

Would be nice to have a list of on-chain txs (in-progress/confirmed) somewhere.

**Comment by aaronbarnardsound** [comment]
Yeah that is less than ideal. Will look in to this and get it fixed!

Proper onchain support with a full listing of all transactions and details is coming in v2 which should hopefully not be too far away.
